package org.javasoft.ciclope.persistence;
// Generated 27-apr-2016 0.09.05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private String nome;
     private String cognome;
     private String cellulare;
     private String localita;
     private Set praticas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String nome, String cognome) {
        this.nome = nome;
        this.cognome = cognome;
    }
    public Cliente(String nome, String cognome, String cellulare, String localita, Set praticas) {
       this.nome = nome;
       this.cognome = cognome;
       this.cellulare = cellulare;
       this.localita = localita;
       this.praticas = praticas;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCognome() {
        return this.cognome;
    }
    
    public void setCognome(String cognome) {
        this.cognome = cognome;
    }
    public String getCellulare() {
        return this.cellulare;
    }
    
    public void setCellulare(String cellulare) {
        this.cellulare = cellulare;
    }
    public String getLocalita() {
        return this.localita;
    }
    
    public void setLocalita(String localita) {
        this.localita = localita;
    }
    public Set getPraticas() {
        return this.praticas;
    }
    
    public void setPraticas(Set praticas) {
        this.praticas = praticas;
    }




}


