package org.javasoft.ciclope.persistence;
// Generated 10-nov-2016 22.50.10 by Hibernate Tools 4.3.1

/**
 * Lavoripratichecustom generated by hbm2java
 */
public class Lavoripratichecustom  implements java.io.Serializable {


     private Integer id;
     private Categoriatipolavoro categoriatipolavoro;
     private Pratica pratica;
     private String descrizione;

    public Lavoripratichecustom() {
    }

    public Lavoripratichecustom(Categoriatipolavoro categoriatipolavoro, Pratica pratica, String descrizione) {
       this.categoriatipolavoro = categoriatipolavoro;
       this.pratica = pratica;
       this.descrizione = descrizione;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Categoriatipolavoro getCategoriatipolavoro() {
        return this.categoriatipolavoro;
    }
    
    public void setCategoriatipolavoro(Categoriatipolavoro categoriatipolavoro) {
        this.categoriatipolavoro = categoriatipolavoro;
    }
    public Pratica getPratica() {
        return this.pratica;
    }
    
    public void setPratica(Pratica pratica) {
        this.pratica = pratica;
    }
    public String getDescrizione() {
        return this.descrizione;
    }
    
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }




}


