package org.javasoft.ciclope.persistence;
// Generated 10-nov-2016 22.50.10 by Hibernate Tools 4.3.1



/**
 * MaterialepraticaId generated by hbm2java
 */
public class MaterialepraticaId  implements java.io.Serializable {


     private int pratica;
     private int articolo;

    public MaterialepraticaId() {
    }

    public MaterialepraticaId(int pratica, int articolo) {
       this.pratica = pratica;
       this.articolo = articolo;
    }
   
    public int getPratica() {
        return this.pratica;
    }
    
    public void setPratica(int pratica) {
        this.pratica = pratica;
    }
    public int getArticolo() {
        return this.articolo;
    }
    
    public void setArticolo(int articolo) {
        this.articolo = articolo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MaterialepraticaId) ) return false;
		 MaterialepraticaId castOther = ( MaterialepraticaId ) other; 
         
		 return (this.getPratica()==castOther.getPratica())
 && (this.getArticolo()==castOther.getArticolo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPratica();
         result = 37 * result + this.getArticolo();
         return result;
   }   


}


