package org.javasoft.ciclope.persistence;
// Generated 10-nov-2016 22.50.10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Materialepratica generated by hbm2java
 */
public class Materialepratica  implements java.io.Serializable {


     private MaterialepraticaId id;
     private Articolo articolo;
     private Pratica pratica;
     private BigDecimal quantitaConsumata;

    public Materialepratica() {
    }

	
    public Materialepratica(MaterialepraticaId id, Articolo articolo, Pratica pratica) {
        this.id = id;
        this.articolo = articolo;
        this.pratica = pratica;
    }
    public Materialepratica(MaterialepraticaId id, Articolo articolo, Pratica pratica, BigDecimal quantitaConsumata) {
       this.id = id;
       this.articolo = articolo;
       this.pratica = pratica;
       this.quantitaConsumata = quantitaConsumata;
    }
   
    public MaterialepraticaId getId() {
        return this.id;
    }
    
    public void setId(MaterialepraticaId id) {
        this.id = id;
    }
    public Articolo getArticolo() {
        return this.articolo;
    }
    
    public void setArticolo(Articolo articolo) {
        this.articolo = articolo;
    }
    public Pratica getPratica() {
        return this.pratica;
    }
    
    public void setPratica(Pratica pratica) {
        this.pratica = pratica;
    }
    public BigDecimal getQuantitaConsumata() {
        return this.quantitaConsumata;
    }
    
    public void setQuantitaConsumata(BigDecimal quantitaConsumata) {
        this.quantitaConsumata = quantitaConsumata;
    }




}


