package org.javasoft.ciclope.persistence;
// Generated 10-nov-2016 22.50.10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Orelavorate generated by hbm2java
 */
public class Orelavorate  implements java.io.Serializable {


     private Integer idOreLavorate;
     private Personale personale;
     private Pratica pratica;
     private BigDecimal ore;
     private Date giornata;

    public Orelavorate() {
    }

	
    public Orelavorate(Personale personale, Pratica pratica, Date giornata) {
        this.personale = personale;
        this.pratica = pratica;
        this.giornata = giornata;
    }
    public Orelavorate(Personale personale, Pratica pratica, BigDecimal ore, Date giornata) {
       this.personale = personale;
       this.pratica = pratica;
       this.ore = ore;
       this.giornata = giornata;
    }
   
    public Integer getIdOreLavorate() {
        return this.idOreLavorate;
    }
    
    public void setIdOreLavorate(Integer idOreLavorate) {
        this.idOreLavorate = idOreLavorate;
    }
    public Personale getPersonale() {
        return this.personale;
    }
    
    public void setPersonale(Personale personale) {
        this.personale = personale;
    }
    public Pratica getPratica() {
        return this.pratica;
    }
    
    public void setPratica(Pratica pratica) {
        this.pratica = pratica;
    }
    public BigDecimal getOre() {
        return this.ore;
    }
    
    public void setOre(BigDecimal ore) {
        this.ore = ore;
    }
    public Date getGiornata() {
        return this.giornata;
    }
    
    public void setGiornata(Date giornata) {
        this.giornata = giornata;
    }




}


