package org.javasoft.ciclope.persistence;
// Generated 27-apr-2016 0.09.05 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Orelavorate generated by hbm2java
 */
public class Orelavorate  implements java.io.Serializable {


     private int idOreLavorate;
     private Personale personale;
     private Pratica pratica;
     private Byte ore;
     private Date giornata;

    public Orelavorate() {
    }

	
    public Orelavorate(int idOreLavorate, Personale personale, Pratica pratica) {
        this.idOreLavorate = idOreLavorate;
        this.personale = personale;
        this.pratica = pratica;
    }
    public Orelavorate(int idOreLavorate, Personale personale, Pratica pratica, Byte ore, Date giornata) {
       this.idOreLavorate = idOreLavorate;
       this.personale = personale;
       this.pratica = pratica;
       this.ore = ore;
       this.giornata = giornata;
    }
   
    public int getIdOreLavorate() {
        return this.idOreLavorate;
    }
    
    public void setIdOreLavorate(int idOreLavorate) {
        this.idOreLavorate = idOreLavorate;
    }
    public Personale getPersonale() {
        return this.personale;
    }
    
    public void setPersonale(Personale personale) {
        this.personale = personale;
    }
    public Pratica getPratica() {
        return this.pratica;
    }
    
    public void setPratica(Pratica pratica) {
        this.pratica = pratica;
    }
    public Byte getOre() {
        return this.ore;
    }
    
    public void setOre(Byte ore) {
        this.ore = ore;
    }
    public Date getGiornata() {
        return this.giornata;
    }
    
    public void setGiornata(Date giornata) {
        this.giornata = giornata;
    }




}


