package org.javasoft.ciclope.persistence;
// Generated 27-apr-2016 0.09.05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Personale generated by hbm2java
 */
public class Personale  implements java.io.Serializable {


     private Integer idPersonale;
     private String nome;
     private String cognome;
     private String posizione;
     private Set orelavorates = new HashSet(0);

    public Personale() {
    }

	
    public Personale(String nome, String cognome, String posizione) {
        this.nome = nome;
        this.cognome = cognome;
        this.posizione = posizione;
    }
    public Personale(String nome, String cognome, String posizione, Set orelavorates) {
       this.nome = nome;
       this.cognome = cognome;
       this.posizione = posizione;
       this.orelavorates = orelavorates;
    }
   
    public Integer getIdPersonale() {
        return this.idPersonale;
    }
    
    public void setIdPersonale(Integer idPersonale) {
        this.idPersonale = idPersonale;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCognome() {
        return this.cognome;
    }
    
    public void setCognome(String cognome) {
        this.cognome = cognome;
    }
    public String getPosizione() {
        return this.posizione;
    }
    
    public void setPosizione(String posizione) {
        this.posizione = posizione;
    }
    public Set getOrelavorates() {
        return this.orelavorates;
    }
    
    public void setOrelavorates(Set orelavorates) {
        this.orelavorates = orelavorates;
    }




}


