package org.javasoft.ciclope.persistence;
// Generated 10-nov-2016 22.50.10 by Hibernate Tools 4.3.1

/**
 * Pratichespeciali generated by hbm2java
 */
public class Pratichespeciali  implements java.io.Serializable {


     private int idPraticaSpeciale;
     private String descrizione;

    public Pratichespeciali() {
    }

    public Pratichespeciali(int idPraticaSpeciale, String descrizione) {
       this.idPraticaSpeciale = idPraticaSpeciale;
       this.descrizione = descrizione;
    }
   
    public int getIdPraticaSpeciale() {
        return this.idPraticaSpeciale;
    }
    
    public void setIdPraticaSpeciale(int idPraticaSpeciale) {
        this.idPraticaSpeciale = idPraticaSpeciale;
    }
    public String getDescrizione() {
        return this.descrizione;
    }
    
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }




}


