package org.javasoft.ciclope.persistence;
// Generated 10-nov-2016 22.50.10 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pratica generated by hbm2java
 */
public class Pratica  implements java.io.Serializable {


     private Integer idPratica;
     private Cliente cliente;
     private Veicolo veicolo;
     private String arrivo;
     private Date dataArrivo;
     private String uscita;
     private Date dataUscita;
     private String lavoriSegnalati;
     private String numeroFattura;
     private Date dataFattura;
     private Boolean preventivoLavori;
     private Boolean revisioneMctc;
     private Boolean collaudoUsl;
     private Boolean registroDiControllo;
     private Date preventivoLavoriData;
     private Date revisioneMctcData;
     private Date collaudoUslData;
     private Date registroDiControlloData;
     private Integer ore;
     private Integer kilometraggio;
     private String clienteTemporaneo;
     private String veicoloTemporaneo;
     private Set lavoripratichecustoms = new HashSet(0);
     private Set lavoripratichestandards = new HashSet(0);
     private Set orelavorates = new HashSet(0);
     private Set materialepraticas = new HashSet(0);

    public Pratica() {
    }

    public Pratica(Cliente cliente, Veicolo veicolo, String arrivo, Date dataArrivo, String uscita, Date dataUscita, String lavoriSegnalati, String numeroFattura, Date dataFattura, Boolean preventivoLavori, Boolean revisioneMctc, Boolean collaudoUsl, Boolean registroDiControllo, Date preventivoLavoriData, Date revisioneMctcData, Date collaudoUslData, Date registroDiControlloData, Integer ore, Integer kilometraggio, String clienteTemporaneo, String veicoloTemporaneo, Set lavoripratichecustoms, Set lavoripratichestandards, Set orelavorates, Set materialepraticas) {
       this.cliente = cliente;
       this.veicolo = veicolo;
       this.arrivo = arrivo;
       this.dataArrivo = dataArrivo;
       this.uscita = uscita;
       this.dataUscita = dataUscita;
       this.lavoriSegnalati = lavoriSegnalati;
       this.numeroFattura = numeroFattura;
       this.dataFattura = dataFattura;
       this.preventivoLavori = preventivoLavori;
       this.revisioneMctc = revisioneMctc;
       this.collaudoUsl = collaudoUsl;
       this.registroDiControllo = registroDiControllo;
       this.preventivoLavoriData = preventivoLavoriData;
       this.revisioneMctcData = revisioneMctcData;
       this.collaudoUslData = collaudoUslData;
       this.registroDiControlloData = registroDiControlloData;
       this.ore = ore;
       this.kilometraggio = kilometraggio;
       this.clienteTemporaneo = clienteTemporaneo;
       this.veicoloTemporaneo = veicoloTemporaneo;
       this.lavoripratichecustoms = lavoripratichecustoms;
       this.lavoripratichestandards = lavoripratichestandards;
       this.orelavorates = orelavorates;
       this.materialepraticas = materialepraticas;
    }
   
    public Integer getIdPratica() {
        return this.idPratica;
    }
    
    public void setIdPratica(Integer idPratica) {
        this.idPratica = idPratica;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Veicolo getVeicolo() {
        return this.veicolo;
    }
    
    public void setVeicolo(Veicolo veicolo) {
        this.veicolo = veicolo;
    }
    public String getArrivo() {
        return this.arrivo;
    }
    
    public void setArrivo(String arrivo) {
        this.arrivo = arrivo;
    }
    public Date getDataArrivo() {
        return this.dataArrivo;
    }
    
    public void setDataArrivo(Date dataArrivo) {
        this.dataArrivo = dataArrivo;
    }
    public String getUscita() {
        return this.uscita;
    }
    
    public void setUscita(String uscita) {
        this.uscita = uscita;
    }
    public Date getDataUscita() {
        return this.dataUscita;
    }
    
    public void setDataUscita(Date dataUscita) {
        this.dataUscita = dataUscita;
    }
    public String getLavoriSegnalati() {
        return this.lavoriSegnalati;
    }
    
    public void setLavoriSegnalati(String lavoriSegnalati) {
        this.lavoriSegnalati = lavoriSegnalati;
    }
    public String getNumeroFattura() {
        return this.numeroFattura;
    }
    
    public void setNumeroFattura(String numeroFattura) {
        this.numeroFattura = numeroFattura;
    }
    public Date getDataFattura() {
        return this.dataFattura;
    }
    
    public void setDataFattura(Date dataFattura) {
        this.dataFattura = dataFattura;
    }
    public Boolean getPreventivoLavori() {
        return this.preventivoLavori;
    }
    
    public void setPreventivoLavori(Boolean preventivoLavori) {
        this.preventivoLavori = preventivoLavori;
    }
    public Boolean getRevisioneMctc() {
        return this.revisioneMctc;
    }
    
    public void setRevisioneMctc(Boolean revisioneMctc) {
        this.revisioneMctc = revisioneMctc;
    }
    public Boolean getCollaudoUsl() {
        return this.collaudoUsl;
    }
    
    public void setCollaudoUsl(Boolean collaudoUsl) {
        this.collaudoUsl = collaudoUsl;
    }
    public Boolean getRegistroDiControllo() {
        return this.registroDiControllo;
    }
    
    public void setRegistroDiControllo(Boolean registroDiControllo) {
        this.registroDiControllo = registroDiControllo;
    }
    public Date getPreventivoLavoriData() {
        return this.preventivoLavoriData;
    }
    
    public void setPreventivoLavoriData(Date preventivoLavoriData) {
        this.preventivoLavoriData = preventivoLavoriData;
    }
    public Date getRevisioneMctcData() {
        return this.revisioneMctcData;
    }
    
    public void setRevisioneMctcData(Date revisioneMctcData) {
        this.revisioneMctcData = revisioneMctcData;
    }
    public Date getCollaudoUslData() {
        return this.collaudoUslData;
    }
    
    public void setCollaudoUslData(Date collaudoUslData) {
        this.collaudoUslData = collaudoUslData;
    }
    public Date getRegistroDiControlloData() {
        return this.registroDiControlloData;
    }
    
    public void setRegistroDiControlloData(Date registroDiControlloData) {
        this.registroDiControlloData = registroDiControlloData;
    }
    public Integer getOre() {
        return this.ore;
    }
    
    public void setOre(Integer ore) {
        this.ore = ore;
    }
    public Integer getKilometraggio() {
        return this.kilometraggio;
    }
    
    public void setKilometraggio(Integer kilometraggio) {
        this.kilometraggio = kilometraggio;
    }
    public String getClienteTemporaneo() {
        return this.clienteTemporaneo;
    }
    
    public void setClienteTemporaneo(String clienteTemporaneo) {
        this.clienteTemporaneo = clienteTemporaneo;
    }
    public String getVeicoloTemporaneo() {
        return this.veicoloTemporaneo;
    }
    
    public void setVeicoloTemporaneo(String veicoloTemporaneo) {
        this.veicoloTemporaneo = veicoloTemporaneo;
    }
    public Set getLavoripratichecustoms() {
        return this.lavoripratichecustoms;
    }
    
    public void setLavoripratichecustoms(Set lavoripratichecustoms) {
        this.lavoripratichecustoms = lavoripratichecustoms;
    }
    public Set getLavoripratichestandards() {
        return this.lavoripratichestandards;
    }
    
    public void setLavoripratichestandards(Set lavoripratichestandards) {
        this.lavoripratichestandards = lavoripratichestandards;
    }
    public Set getOrelavorates() {
        return this.orelavorates;
    }
    
    public void setOrelavorates(Set orelavorates) {
        this.orelavorates = orelavorates;
    }
    public Set getMaterialepraticas() {
        return this.materialepraticas;
    }
    
    public void setMaterialepraticas(Set materialepraticas) {
        this.materialepraticas = materialepraticas;
    }




}


