package org.javasoft.ciclope.persistence;
// Generated 27-apr-2016 0.09.05 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pratica generated by hbm2java
 */
public class Pratica  implements java.io.Serializable {


     private int idPratica;
     private Cliente cliente;
     private String arrivo;
     private Date dataArrivo;
     private String uscita;
     private Date dataUscita;
     private String lavoriSegnalati;
     private String numeroFattura;
     private Date dataFattura;
     private Boolean preventivoLavori;
     private Boolean revisioneMctc;
     private Boolean collaudoUsl;
     private Boolean registroDiControllo;
     private Date preventivoLavoriData;
     private Date revisioneMctcData;
     private Date collaudoUslData;
     private Date registroDiControlloData;
     private Integer ore;
     private Integer kilometraggio;
     private Set orelavorates = new HashSet(0);
     private Set lavoropraticas = new HashSet(0);
     private Set materialepraticas = new HashSet(0);

    public Pratica() {
    }

	
    public Pratica(int idPratica, Cliente cliente) {
        this.idPratica = idPratica;
        this.cliente = cliente;
    }
    public Pratica(int idPratica, Cliente cliente, String arrivo, Date dataArrivo, String uscita, Date dataUscita, String lavoriSegnalati, String numeroFattura, Date dataFattura, Boolean preventivoLavori, Boolean revisioneMctc, Boolean collaudoUsl, Boolean registroDiControllo, Date preventivoLavoriData, Date revisioneMctcData, Date collaudoUslData, Date registroDiControlloData, Set orelavorates, Set lavoropraticas, Set materialepraticas, Integer ore, Integer kilometraggio) {
       this.idPratica = idPratica;
       this.cliente = cliente;
       this.arrivo = arrivo;
       this.dataArrivo = dataArrivo;
       this.uscita = uscita;
       this.dataUscita = dataUscita;
       this.lavoriSegnalati = lavoriSegnalati;
       this.numeroFattura = numeroFattura;
       this.dataFattura = dataFattura;
       this.preventivoLavori = preventivoLavori;
       this.revisioneMctc = revisioneMctc;
       this.collaudoUsl = collaudoUsl;
       this.registroDiControllo = registroDiControllo;
       this.preventivoLavoriData = preventivoLavoriData;
       this.revisioneMctcData = revisioneMctcData;
       this.collaudoUslData = collaudoUslData;
       this.registroDiControlloData = registroDiControlloData;
       this.orelavorates = orelavorates;
       this.lavoropraticas = lavoropraticas;
       this.materialepraticas = materialepraticas;
       this.ore = ore;
       this.kilometraggio = kilometraggio;
    }
   
    public int getIdPratica() {
        return this.idPratica;
    }
    
    public void setIdPratica(int idPratica) {
        this.idPratica = idPratica;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getArrivo() {
        return this.arrivo;
    }
    
    public void setArrivo(String arrivo) {
        this.arrivo = arrivo;
    }
    public Date getDataArrivo() {
        return this.dataArrivo;
    }
    
    public void setDataArrivo(Date dataArrivo) {
        this.dataArrivo = dataArrivo;
    }
    public String getUscita() {
        return this.uscita;
    }
    
    public void setUscita(String uscita) {
        this.uscita = uscita;
    }
    public Date getDataUscita() {
        return this.dataUscita;
    }
    
    public void setDataUscita(Date dataUscita) {
        this.dataUscita = dataUscita;
    }
    public String getLavoriSegnalati() {
        return this.lavoriSegnalati;
    }
    
    public void setLavoriSegnalati(String lavoriSegnalati) {
        this.lavoriSegnalati = lavoriSegnalati;
    }
    public String getNumeroFattura() {
        return this.numeroFattura;
    }
    
    public void setNumeroFattura(String numeroFattura) {
        this.numeroFattura = numeroFattura;
    }
    public Date getDataFattura() {
        return this.dataFattura;
    }
    
    public void setDataFattura(Date dataFattura) {
        this.dataFattura = dataFattura;
    }
    public Boolean getPreventivoLavori() {
        return this.preventivoLavori;
    }
    
    public void setPreventivoLavori(Boolean preventivoLavori) {
        this.preventivoLavori = preventivoLavori;
    }
    public Boolean getRevisioneMctc() {
        return this.revisioneMctc;
    }
    
    public void setRevisioneMctc(Boolean revisioneMctc) {
        this.revisioneMctc = revisioneMctc;
    }
    public Boolean getCollaudoUsl() {
        return this.collaudoUsl;
    }
    
    public void setCollaudoUsl(Boolean collaudoUsl) {
        this.collaudoUsl = collaudoUsl;
    }
    public Boolean getRegistroDiControllo() {
        return this.registroDiControllo;
    }
    
    public void setRegistroDiControllo(Boolean registroDiControllo) {
        this.registroDiControllo = registroDiControllo;
    }
    public Date getPreventivoLavoriData() {
        return this.preventivoLavoriData;
    }
    
    public void setPreventivoLavoriData(Date preventivoLavoriData) {
        this.preventivoLavoriData = preventivoLavoriData;
    }
    public Date getRevisioneMctcData() {
        return this.revisioneMctcData;
    }
    
    public void setRevisioneMctcData(Date revisioneMctcData) {
        this.revisioneMctcData = revisioneMctcData;
    }
    public Date getCollaudoUslData() {
        return this.collaudoUslData;
    }
    
    public void setCollaudoUslData(Date collaudoUslData) {
        this.collaudoUslData = collaudoUslData;
    }
    public Date getRegistroDiControlloData() {
        return this.registroDiControlloData;
    }
    
    public void setRegistroDiControlloData(Date registroDiControlloData) {
        this.registroDiControlloData = registroDiControlloData;
    }
    public Set getOrelavorates() {
        return this.orelavorates;
    }
    
    public void setOrelavorates(Set orelavorates) {
        this.orelavorates = orelavorates;
    }
    public Set getLavoropraticas() {
        return this.lavoropraticas;
    }
    
    public void setLavoropraticas(Set lavoropraticas) {
        this.lavoropraticas = lavoropraticas;
    }
    public Set getMaterialepraticas() {
        return this.materialepraticas;
    }
    
    public void setMaterialepraticas(Set materialepraticas) {
        this.materialepraticas = materialepraticas;
    }
    
    public void setOre(Integer ore) {
        this.ore = ore;
    }
    
    public Integer getOre() {
        return this.ore;
    }
    
    public void setKilometraggio(Integer kilometraggio){
        this.kilometraggio = kilometraggio;
    }
    
    public Integer getKilometraggio(){
        return this.kilometraggio;
    }
    
}


