package org.javasoft.ciclope.persistence;
// Generated 10-nov-2016 22.50.10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipolavoro generated by hbm2java
 */
public class Tipolavoro  implements java.io.Serializable {


     private Integer idTipoLavoro;
     private Categoriatipolavoro categoriatipolavoro;
     private String codice;
     private String descrizione;
     private Set lavoripratichestandards = new HashSet(0);

    public Tipolavoro() {
    }

	
    public Tipolavoro(Categoriatipolavoro categoriatipolavoro, String codice) {
        this.categoriatipolavoro = categoriatipolavoro;
        this.codice = codice;
    }
    public Tipolavoro(Categoriatipolavoro categoriatipolavoro, String codice, String descrizione, Set lavoripratichestandards) {
       this.categoriatipolavoro = categoriatipolavoro;
       this.codice = codice;
       this.descrizione = descrizione;
       this.lavoripratichestandards = lavoripratichestandards;
    }
   
    public Integer getIdTipoLavoro() {
        return this.idTipoLavoro;
    }
    
    public void setIdTipoLavoro(Integer idTipoLavoro) {
        this.idTipoLavoro = idTipoLavoro;
    }
    public Categoriatipolavoro getCategoriatipolavoro() {
        return this.categoriatipolavoro;
    }
    
    public void setCategoriatipolavoro(Categoriatipolavoro categoriatipolavoro) {
        this.categoriatipolavoro = categoriatipolavoro;
    }
    public String getCodice() {
        return this.codice;
    }
    
    public void setCodice(String codice) {
        this.codice = codice;
    }
    public String getDescrizione() {
        return this.descrizione;
    }
    
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }
    public Set getLavoripratichestandards() {
        return this.lavoripratichestandards;
    }
    
    public void setLavoripratichestandards(Set lavoripratichestandards) {
        this.lavoripratichestandards = lavoripratichestandards;
    }




}


